### ISSUE TITLE
Error starting restore session

### ISSUE THREAD

**Issue by dmontesdrp** [VeeamHub/vbo365-rest-self-service#10]
Hello after upgrade the portal and Veeam for office 365 a Ihave an error Error starting restore session, i thought it was for the time zone after that I resolve timezone issue but the error still apearing

any sugestion

Regards

**Comment by nielsengelen** [comment]
Did you correctly install both Veeam Explorer packages which came with the download? Which version are you running?

**Comment by dmontesdrp** [comment]
I'm working with the version 4 of veeam for office365 and I updated de portal

**Comment by nielsengelen** [comment]
As suggested, can you verify you also updated the Veeam Explorers? If you were using v3 before with the portal, you also have to update the config.php file and change the version from v3 to v4 (unless u did a fresh download of the code).

**Comment by dmontesdrp** [comment]
The portal was updated before the veeam update

**Comment by nielsengelen** [comment]
And can u confirm you also updated the explorers? Can u also double check the Veeam RESTful API service is running?

**Comment by dmontesdrp** [comment]
Hello, the portal works after update but we're stlill having issues at the moment to explore the last backup it doesn't show the last mail it only shows 2 or 3 mails but no completed

regards

**Comment by nielsengelen** [comment]
What's the time difference between the restore points? It could be the restore was started with the restore point BEFORE the last backup which explains this behavior.

**Comment by dmontesdrp** [comment]
There are 4 hours of difference between the portal and the explorer, but the portal does not show all the items after the backup, at the moment we are using the last backup but all the mails aren't showing all

in the explorer i don't have this issue its only in the portal

**Comment by nielsengelen** [comment]
Would it be possible to contact me via mail (niels.engelen@veeam.com) so we can maybe arrange a remote call to see what the issue is? It will go faster that way.
