### ISSUE TITLE
VBO 4.0 ? 

### ISSUE THREAD

**Issue by JosserandM** [VeeamHub/vbo365-rest-self-service#12]
Hey, did you test the selfservice using VBO 4.0 ?
our test are reallly far far away from your screenshot, it is like nothing is working fine

<img width="770" alt="Capture d’écran 2020-03-20 à 14 29 13" src="https://user-images.githubusercontent.com/38564367/77173352-ac493c80-6abf-11ea-82f3-4c2220875f8f.png">
<img width="518" alt="Capture d’écran 2020-03-19 à 14 40 46" src="https://user-images.githubusercontent.com/38564367/77173364-af442d00-6abf-11ea-8acf-1b511dc3d15c.png">

**Comment by nielsengelen** [comment]
v4 works. I am not sure what you are trying to explain with the screenshots as the top one shows the Exchange page and below is a OneDrive view from Teams. 

If you go to the OneDrive page, you should be able to start the restore session and see the folder (if it is in the backup file).

**Comment by JosserandM** [comment]
Sorry, the last screen is a mistake, all the exchanghe part, or onedrive part show nothing correctly, we are not able to browser anything, maybee we miss something.

**Comment by nielsengelen** [comment]
If u select the organization in the left menu, you should be able to start a restore via the available backups.
