### ISSUE TITLE
The portal does not show the last backups

### ISSUE THREAD

**Issue by dmontesdrp** [VeeamHub/vbo365-rest-self-service#13]
Good day.

Last week, I was testing the portal with the new version in that moment everithing was ok, I made a comparison between the portal and the exhange explorer both didn't have the same number of mails after make the backup.

any sugest.

Regards

**Comment by nielsengelen** [comment]
Restore sessions via the portal are started with 2 parameters:
- Show Deleted Versions
- Show All Versions

It is possible, Veeam Explorer doesn't use this parameter and therefore you see the mentioned difference. If you use a previous restore point via the Veeam Explorer, do you see the same items?

For now, this is hardcoded but I have it on my todo to make this a flexible option
