### ISSUE TITLE
VBO Requirements

### ISSUE THREAD

**Issue by bgre033** [VeeamHub/vbo365-rest-self-service#14]
Hello,

What are the requirements from the Veeam Backup for Microsoft Office 365 side? For example, what needs to be configured to allow tenants to log in and only view their own data?

Thanks,

Gregor

**Comment by nielsengelen** [comment]
You will have to configure 2 things:
- [RESTful API settings](https://helpcenter.veeam.com/docs/vbo365/guide/vbo_rest_api_settings.html?ver=40)
- [Authentication settings](https://helpcenter.veeam.com/docs/vbo365/guide/vbo_authentication_settings.html?ver=40)
