### ISSUE TITLE
Restore users

### ISSUE THREAD

**Issue by swamp2k** [VeeamHub/vbo365-rest-self-service#15]
Hi,

We have noticed in the newest version of VBO GUI that multiple users can now be used for restore in office 360.
(you click a link to https://microsoft.com/devicelogin -> login with o365 admin-> type a code provided by VBO)

I see this is a rather new feature, and the latest update to this project is some 6-7 months ago.
Is this new feature supported?  Or is it maybe coming?

**Comment by nielsengelen** [comment]
Hi, correct this got added in the latest update 4c but hasn't been implemented yet in the portal. I'm working on implementing it but I can't give an ETA when this will be available (as it takes some time to assure it works correctly).

**Comment by swamp2k** [comment]
Thanks for the reply @nielsengelen 
We are looking forward to it, thanks.
