### ISSUE TITLE
User login using modern authentication

### ISSUE THREAD

**Issue by ecruces** [VeeamHub/vbo365-rest-self-service#16]
Hi,

First of all i want to thank you Niels for this good job. Our problem is that we just tried with 365 modern authentication and it's not working to access on the selfservice. 

**Describe the bug**
When i access with username and credential that it works on 365 website it says "Authorization Error: Invalid credential"

**To Reproduce**
1. On Veeam 365 Configure Organization with modern authentication
2. Use an existing Azure Ad Application
3. Set the username to impernation and application id
4. Configure backup job and execute
5. Try to access on Veeam Selfservice with usernname and password or application id and it says "Authorization Error: Invalid credential"

**Expected behavior**
I expect to access

**Screenshots**
![Captura](https://user-images.githubusercontent.com/58166596/89515325-3e37b480-d7d7-11ea-868b-d1c6db2e4a09.JPG)

**Desktop (please complete the following information):**
 - OS: Windows 10, Android 10
 - Browser Chrome, Firefox
 - Version 84.0.4147.105 and 79.0

**Additional context**
Thanks in advance!

**Comment by nielsengelen** [comment]
Hi @ecruces - this issue has also been reported on the main branch (https://github.com/nielsengelen/vbo365-rest/issues/59). This is a known issue for now and is on my task list to find a solution, for now I don't have any workaround.

**Comment by erwinlinker17** [comment]
@ecruces when you log in with the username and the "App password" you should be able to login.

**Comment by nielsengelen** [comment]
MFA with application ID and tenant ID has been added in v4.2 release.
