### ISSUE TITLE
“500 Restore failed: JSON is not well-formed.” when performing restores

### ISSUE THREAD

**Issue by WvT-at-Interconnect** [VeeamHub/vbo365-rest-self-service#17]
**Describe the bug**
When any restore is performed using the portal i get an error " I get an error “500 Restore failed: JSON is not well-formed.”

**To Reproduce**
1. Login to the portal
2. Click on 'OneDrive'
3. Select an Organization
4. Select a backup
5. Choose object(s) to restore
6. Choose 'to Original location'
7. Put in credentials
8. Receive the error message '500 Restore failed: JSON is not well-formed'

**Expected behavior**
Start restore to original location

**Screenshots**
![500 Restore failed](https://user-images.githubusercontent.com/70750120/92224906-c8d90580-eea2-11ea-9a1e-e1544186eb11.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome, Firefox
 - Version: Chrome 85, Firefox 80

**Comment by nielsengelen** [comment]
Reason found via mail; related due to specific chars in the password and noted as an improvement for the portal code.
