### ISSUE TITLE
Users mailboxes not displayed in Restore session on Portal but appear in Console 

### ISSUE THREAD

**Issue by charris-crs** [VeeamHub/vbo365-rest-self-service#18]
We have a customer with 1900+ mailboxes.
When running a Restore from the Veeam VBO console all Mailboxes appear
When running the Same Restore from the portal some of the mailboxes are missing.

We are running latest version of VBO 4.0.1.545 and latest version of the Portal on Ubuntu 18.04

**Comment by nielsengelen** [comment]
Do you have an idea of how many won't load? I may need to perform a remote call for insight on this issue.

**Comment by charris-crs** [comment]
Hello Niels
there are 980 mailboxes listed so there are approx 1,000 missing.
Best regards
Clive

**Comment by craydusk** [comment]
Hello Niels,

Do you have a solution because I have exactly the same problem? I'm running the latest version of VBO (5.01.225) and the latest version of the portal on Amazon Linux 2 AMI.

Best regards.

Yoann.

**Comment by nielsengelen** [comment]
Hi Yoann, 

Not directly, this is hard to tell without insight. Could you contact me via mail for additional details? You can reach me via niels dot engelen at veeam dot com.
