### ISSUE TITLE
Is it possible to include a filter box at the top of the Restore page

### ISSUE THREAD

**Issue by charris-crs** [VeeamHub/vbo365-rest-self-service#19]
We have a Customer with over 1900 users and rather than have to scroll down to find the mailbox it would be nice to have a filter box ate the top so we can enter their name and it dynamically reduces the available mailbox as each letter is typed.

E.g. If the letter S is typed in the filter box all mailboxes beginning with S are displayed. If ST is typed then only those starting ST are displayed and so on.

With10 customers signed up for VBO with the portal it would be good to see this excellent portal developed further.

Keep up the good work.

Thanks

**Comment by nielsengelen** [comment]
This is a great request. I don't know if it could be easily achieved right now as there is no option to filter within the VBO API like this. This would require a custom solution and I'll have to give it some thoughts.
