### ISSUE TITLE
Site appearance doesn't look right on my system

### ISSUE THREAD

**Issue by GreyArea765** [VeeamHub/vbo365-rest-self-service#2]
I've gone through the process of deploying this to a CentOS 7 system, but when I load the page it doesn't look quite like your screenshots, any suggestions please?

![Capture](https://user-images.githubusercontent.com/24699077/55470081-d7145980-55fe-11e9-9e15-e852c76fbb93.PNG)

**Comment by nielsengelen** [comment]
It looks like the CSS isn't loading for the page. Did you follow all the steps as described in the README? The CSS comes from bootstrap mostly which is installed via the composer command.

**Comment by GreyArea765** [comment]
Thanks for the reply, my exact procedure is here https://gist.github.com/GreyArea765/8ee679fcbab76dfe3b144257b7d5e2ea#file-version2-md

I just repeated the composer install and can see that bootstrap does get installed.

sudo composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 9 installs, 0 updates, 0 removals
  - Installing components/jquery (3.2.0): Downloading (100%)
  - Installing twbs/bootstrap (v3.3.7): Downloading (100%)
  - Installing guzzlehttp/promises (v1.3.1): Downloading (100%)
  - Installing ralouphie/getallheaders (2.0.5): Downloading (100%)
  - Installing psr/http-message (1.0.1): Downloading (100%)
  - Installing guzzlehttp/psr7 (1.5.2): Downloading (100%)
  - Installing guzzlehttp/guzzle (6.3.3): Downloading (100%)
  - Installing psr/log (1.1.0): Downloading (100%)
  - Installing semantic/ui (2.4.1): Downloading (100%)
Writing lock file
Generating autoload files

**Comment by nielsengelen** [comment]
I've just published an updated version with some new features. I suggest you run a Git clone and composer one more time so you have version 3. From the looks of it, everything installs correctly however the css files aren't being loaded. Did u enable mod_rewrite on your apache and can u double check the .htaccess file is available in the directory?
