### ISSUE TITLE
Restore fails

### ISSUE THREAD

**Issue by BrandonBMIT** [VeeamHub/vbo365-rest-self-service#2]
Whenever attempting to restore a mailbox, it is giving an error "failed to restore item" and when attempting to restore a OneDrive: "Failed to find users for tenant account". 

Also, when downloading the email as .msg or .zip for the OneDrive, nothing happens. SharePoint gives "completed with warnings". 

I'm running this on IIS 10 with PHP 7.3.8. 

Has anyone encountered this issue or perhaps can provide some assistance?

**Comment by nielsengelen** [comment]
Did you install the Veeam Explorers correctly? Which VBO version are you running?

**Comment by BrandonBMIT** [comment]
> Did you install the Veeam Explorers correctly? Which VBO version are you running?

I managed to do a successful restore from the Veeam Explorers, so it should be fine? I'm running VBO 3.0.0.422.

**Comment by nielsengelen** [comment]
Best option would be to check the RESTful logs to see what is going wrong when you try to do an export. You can find them under C:\ProgramData\Veeam\Backup365\Logs
