### ISSUE TITLE
Unable to login with tenant account

### ISSUE THREAD

**Issue by jjpothoven** [VeeamHub/vbo365-rest-self-service#20]
Hello,

We have setup a vbo365 server with a few tenants. The vbo server is in a domain and has version 4.0.1.545
VBR 10 is also installed on this server with cloud connect.

We have configured the restful api settings and the authentication settings as described.
They are signed with a commercial wildcard SSL.

The servers are both windows 2019

We have now setup a webserver in a workgroup. This server is able to login with local or a domain admin account.
However if we try to login with a tenant office 365 admin account we are unable to login.

If we use veeam explorers at the tenant site we are able to login with office365 credentials and see only their organization. 

Any suggestions on your side what I missed?

**Comment by nielsengelen** [comment]
Can u check if u enabled the[ authentication settings](https://helpcenter.veeam.com/docs/vbo365/guide/vbo_authentication_settings.html?ver=40)?

**Comment by jjpothoven** [comment]
Yes they are enabled
![image](https://user-images.githubusercontent.com/72129075/94682323-0eafaf00-0325-11eb-950a-491df6673272.png)

**Comment by nielsengelen** [comment]
Do you see any errors happening in the REST API logs (found under C:\ProgramData\Veeam\Backup365\Logs)?

**Comment by jjpothoven** [comment]
There are no errors in de veeam.archiver.rest logfiles(as far as I can see)

**Comment by nielsengelen** [comment]
@jjpothoven Are you using MFA enabled organizations by any chance?

**Comment by jjpothoven** [comment]
Yes, the organizations are mfa enabled however the accounts I tried had mfa disabled

**Comment by nielsengelen** [comment]
Can u drop me an email (niels.engelen@veeam.com) so we can follow up there as I will need to get some more insight in general.
