### ISSUE TITLE
No login to Self-Service-Portal when using Modern Authentication

### ISSUE THREAD

**Issue by carokiel** [VeeamHub/vbo365-rest-self-service#21]
Hi Niels,
I know, this topic pops up every now and then, but here are maybe some more details:
Most customers nowadays enforce multifactor-authentication (MFA) on their Office365 tenants.
With the current version of VBO, Veeam provides a really good connection method to these tenants:
When setting up a new organization in VBO, you just select "Modern Authentication" without the support for legacy and provide the name of the accoun t to create within the Office 365 tenant.  Afterwards, a global admin just has to confirm the first logon of the new account once and VBO configures all the rest.
The downside of this process is however that you don't get any app password for the backup account you create. Therefore, the customer cannot sign on to the self-servcie-portal, as the password is unknown.
Do you have any idea, howto fix this? Is the password somehow revealable from VBO? Or do you see any other chance to solve this?

Best regards,
Caroline

**Comment by nielsengelen** [comment]
Hi Caroline, support for MFA is on the roadmap as it has been requested a few times now (see https://github.com/nielsengelen/vbo365-rest/issues/59 as well). The customer will have to use the application ID and tenant name (*.onmicrosoft.com) and use the same validation as when adding the organization in order to continue.

**Comment by nielsengelen** [comment]
Hey Caroline, just wanted to update you and inform you that MFA support has been added in v4.2 update.
