### ISSUE TITLE
Dashboard with tenant account

### ISSUE THREAD

**Issue by bathced** [VeeamHub/vbo365-rest-self-service#22]
Hi, 

Is-it possible to have access in dashboard and job history when someone connect with him tenant login ? 

Regards, 
Cédric

**Comment by nielsengelen** [comment]
Hi Cédric, this has been requested before but this isn't something which is available via the VBO API as it is. This could be achieved in the current portal but it would require to store admin credentials in the configuration file (or somewhere else) to simulate the same behavior. I may look into this for a next release but I am not a big fan of the idea/workaround.

**Comment by bathced** [comment]
Thx for this return, I just want provide autonomy for my customers on office backup.
