### ISSUE TITLE
MFA Login Problem

### ISSUE THREAD

**Issue by dominikmze** [VeeamHub/vbo365-rest-self-service#23]
Hello,

if I want to log in with an MFA account, this does not work. I get the login code and then authenticate myself with Microsoft, but I am not logged into the interface afterwards. If I then enter the email address directly, I get the error message simple login in Microsoft.

Do you have a solution for that? I look forward to an answer.

**Comment by nielsengelen** [comment]
Duplicate from https://github.com/nielsengelen/vbo365-rest/issues/76
