### ISSUE TITLE
MFA not working

### ISSUE THREAD

**Issue by gingerr6** [VeeamHub/vbo365-rest-self-service#24]
**Describe the bug**
you can enter all the ID's but pressing next doesn't progress 

**To Reproduce**
1. Go to "use mfa login"
if you don't enter any details then you do get an error so the next button is working

**Expected behaviour**
progress to next setp

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: server 2016 IIS
desktop windows 10 same results
 - tried Firefox and edge
 

**Additional context**
most recent veeam and GitHub versions

**Comment by nielsengelen** [comment]
Once you hit the next button, an API call is performed towards Microsoft's API. Could you check if you are running a firewall on the server which is hosting the portal?

**Comment by gingerr6** [comment]
ok, so i have a untangle firewall but it shouldn't be blocking out. i can see outbound to Microsoft

**Comment by gingerr6** [comment]
can i run a CMD or PS to check?

**Comment by nielsengelen** [comment]
The request goes to https://login.microsoftonline.com/ so if you could check if it works without firewall or analyze the logs if something is blocked, it will help.

**Comment by gingerr6** [comment]
so i can see when i hit the next there is a new http request /microsoft.php
HTTP URI | /microsoft.php

**Comment by nielsengelen** [comment]
The portal requires access to microsoftonline.com. Since you state you are running a firewall (or proxy) on it, please verify you can access microsoftonline.com from the server running the portal.

**Comment by gingerr6** [comment]
Hi, i have no outbound blocking i have disabled all services in the FW and still the next button isn't working.

**Comment by gingerr6** [comment]
it works for a restore, as in i click exchange pick Tennant and i get the modern auth code etc.
the restore fails but thats another case.

**Comment by nielsengelen** [comment]
Can u open up a developer console on your browser (F12 in Chrome and Firefox), reload the index and perform the steps again (Use MFA login -> hit next). Do you see any errors or warnings?

**Comment by gingerr6** [comment]
Uncaught SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
    <anonymous> https://FQND/index.php:230
    jQuery 7
        c
        fireWith
        l
        o
        send
        ajax
        i
    <anonymous> https://FQND/index.php:229
    jQuery 2
        dispatch
        handle
index.php:230:26

**Comment by nielsengelen** [comment]
Any chance u can contact me via mail (niels.engelen@veeam.com) about this as I'll need to have some form of access to the login page to try this? Thanks.
