### ISSUE TITLE
Restore to original location not working:

### ISSUE THREAD

**Issue by gingerr6** [VeeamHub/vbo365-rest-self-service#27]
20/11/2020 09:21:36   91 (1632) Action failed (action: restoretoOriginallocation, data: items, error: The server did not provide a meaningful reply; this might be caused by a contract mismatch, a premature session shutdown or an internal server error.)

**Comment by gingerr6** [comment]
20/11/2020 09:23:53   98 (5800)   Action: explore
20/11/2020 09:23:53   98 (5800) Action started (action: explore, data: organizations, API version: V4)
20/11/2020 09:23:53   98 (5800) Connecting to Veeam Backup for Office 365 server using Windows authentication: 127.0.0.1 (port: 9194, user name: administrator)...
20/11/2020 09:23:53   98 (5800) Connecting to Veeam Backup for Office 365 server at 127.0.0.1:9194...
20/11/2020 09:23:53   98 (5800)   Successfully connected
20/11/2020 09:23:53   98 (5800) Creating restore session with the following parameters:
20/11/2020 09:23:53   98 (5800)   Scope: Organization
20/11/2020 09:23:53   98 (5800)   Organization ID: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
20/11/2020 09:23:53   98 (5800)   Point in time: 20/11/2020 09:00:00
20/11/2020 09:23:53   98 (5800)   ShowDeleted: True
20/11/2020 09:23:53   98 (5800)   ShowAllVersions: True
20/11/2020 09:23:53   98 (5800)   Restore session successfully created
20/11/2020 09:23:53   98 (5800) Restore session created (ID: 0cce4ed7-a094-448d-94cb-f230944b56ac)
20/11/2020 09:23:53   98 (5800) Action completed successfully (action: explore, data: organizations)
20/11/2020 09:23:55   98 (5800) Action started: Get organization (API version: V4)
20/11/2020 09:23:55   98 (5800) Action completed successfully: Get organization
20/11/2020 09:23:55   90 (3900) Action started: Get mailboxes (API version: V4)
20/11/2020 09:23:55   90 (3900) Action completed successfully: Get mailboxes
20/11/2020 09:23:57  151 (5584) Action started: Get organization (API version: V4)
20/11/2020 09:23:57  151 (5584) Action completed successfully: Get organization
20/11/2020 09:23:57  151 (5584) Action started: Get mailboxes (API version: V4)
20/11/2020 09:23:57  151 (5584) Action completed successfully: Get mailboxes
20/11/2020 09:23:57  151 (5584) Action started: Get mailboxes (API version: V4)
20/11/2020 09:23:57  151 (5584) Action completed successfully: Get mailboxes
20/11/2020 09:23:57  151 (5584) Action started: Get folders (API version: V4)
20/11/2020 09:23:58  151 (5584) Action completed successfully: Get folders
20/11/2020 09:24:00   90 (3900) Action started: Get folders (API version: V4)
20/11/2020 09:24:00   90 (3900) Action completed successfully: Get folders
20/11/2020 09:24:00   90 (3900) Action started: Get items (API version: V4)
20/11/2020 09:24:01   90 (3900) Action completed successfully: Get items
20/11/2020 09:24:35   92 (6772) Action started: Get restoreDeviceCode (API version: V4)
20/11/2020 09:24:35   92 (6772) Action completed successfully: Get restoreDeviceCode
20/11/2020 09:25:08   92 (6772)   Action: restoretoOriginallocation
20/11/2020 09:25:08   92 (6772) Action started (action: restoretoOriginallocation, data: item, API version: V4)

09:33 no update in logs and no email restored. VBO shows job still running.

this is restoring 1 email

**Comment by nielsengelen** [comment]
This is an error related to VBO itself and not to the portal. I suggest you contact Veeam support here as I have not seen this error before. It could be related to an issue in your VBO installation or the user account.

**Comment by gingerr6** [comment]
from the VBO the email restores fine?

**Comment by gingerr6** [comment]
OneDrive and SP work absolutely flawlessly...
single email restore never completes.

**Comment by nielsengelen** [comment]
This error happens in the API of VBO. It looks like an issue with the installation of VEX or the API but the error is unclear for me and I suggest you let the logs analyze via Veeam support.
