### ISSUE TITLE
Portal for Teams 

### ISSUE THREAD

**Issue by jantoney** [VeeamHub/vbo365-rest-self-service#28]
**Describe the solution you'd like**
Veeam Office 365 backup has recently released V5 that includes Teams Backup and Restore features. Are there plans to include that here? Either way, are we able to update the Read Me with some info either for or against adding it.

**Describe alternatives you've considered**
Writing it myself, but that's not really going to be a thing given my current skillz

**Comment by nielsengelen** [comment]
Hi, I am working on adding Teams support and some other small improvements. I don't have an ETA on it however Teams is quite a big one in terms of capabilities. I will most likely look into creating a "beta" build first on my personal GitHub and later on launch a final (GA) build. Hopefully, this way I can get some help from the community to find and fix bugs.

**Comment by lmbutault** [comment]
Thanks Niels
exept that self service portal would not allow Teams restores, do you know is actual portal binaries would work with a VBO365 upgraded to V5 with no regressions?
regards,
Louis-Marie

**Comment by nielsengelen** [comment]
If you change the version in the config file from v4 to v5 (if you are running VBO v5), all will work. I performed tests but didn't find any direct bugs this way.

**Comment by lmbutault** [comment]
thanks niels for answer!
