### ISSUE TITLE
Exchange stopped working?

### ISSUE THREAD

**Issue by gingerr6** [VeeamHub/vbo365-rest-self-service#30]
Hi,

latest version and all that did work but now clicking exchange then click explore latest we get users but clicking a user gets blank screen:

PHP Fatal error:  Uncaught Error: Undefined constant "_links" in /app/exchange.php:320

**Comment by nielsengelen** [comment]
Can u tell me the exact VBO version you are using so I can verify this?

**Comment by gingerr6** [comment]
5.0.0.1070

**Comment by nielsengelen** [comment]
Could you send me a copy of the RESTful API logs which can be found in %programdata%\Veeam\Backup365\Logs via niels.engelen@veeam.com? Also, can u verify this is with an existing organization or did u add a new one?

**Comment by nielsengelen** [comment]
Issue has been found and code has been updated to reflect the change.
