### ISSUE TITLE
MFA Login Does nothing

### ISSUE THREAD

**Issue by ostergaardlars** [VeeamHub/vbo365-rest-self-service#31]
**Describe the bug**

**To Reproduce**
2. logn MFA and use the tenant id and the Application id 
3. Next
Uncaught SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
**Expected behavior**

**Screenshots**
![billede](https://user-images.githubusercontent.com/68034832/114166952-a4f50b00-992e-11eb-8d7c-abf99fbce66e.png)

**Desktop (please complete the following information):**
 - windows 2019 
 - All browers

**Smartphone (please complete the following information):**

**Additional context**
Does mak an error if i do not add application id  it says provide your app id

**Comment by nielsengelen** [comment]
Which VBO version are you using? And is this using the latest version of the portal?

**Comment by ostergaardlars** [comment]
Hi Niels,

Using the version download from: https://github.com/VeeamHub/vbo365-rest-self-service
Using 5.0.1.179  of Veeam Backup for Microsoft office 365

Venlig hilsen / Best regards

Lars Østergaard
Teknisk Chef
***@***.***D72FB5.1496C450]
Direct
E-mail
Website
+45 2542 7789
***@***.***
www.mariendalit.dk<https://www.mariendalit.dk>
Mariendal IT A/S
Gasværksvej 44
DK-9000 Aalborg
Tel. +45 9631 7790

Besøg vores opdaterede webshop her: shop.mariendal.dk<https://shop.mariendal.dk/>
Alle priser oplyst i E-mail’s fra Mariendal IT A/S er ekskl. moms, fragt, samt installation, medmindre andet er aftalt eller skrevet.
Mariendal IT A/S henviser i øvrigt til vores generelle handelsbetingelser.
Ethvert tilsendt tilbud, dokumentation eller andre oplysninger må ikke videregives til 3. part, medmindre andet er aftalt.
Fra: Niels Engelen ***@***.***>
Sendt: 12. april 2021 15:54
Til: VeeamHub/vbo365-rest-self-service ***@***.***>
Cc: Lars Østergaard ***@***.***>; Author ***@***.***>
Emne: Re: [VeeamHub/vbo365-rest-self-service] MFA Login Does nothing (#31)


Which VBO version are you using? And is this using the latest version of the portal?

**Comment by nielsengelen** [comment]
I can't directly tell what is causing this as the javascript error isn't really related to the action. It could be a firewall issue or something going wrong in terms of the communication between browser, Microsoft auth or VBO auth. Could you send me an email via niels.engelen@veeam.com so we can look into this using a remote session?
