### ISSUE TITLE
MFA Login not responding

### ISSUE THREAD

**Issue by DavidCGN** [VeeamHub/vbo365-rest-self-service#32]
Hello,

I'm currently struggling to enable the Tenant-Login. I created an Application-ID for a organisation in our vbo365.
I can login in to the portal with the basic authentication. To restore something I use the same Application-ID and it works.
But I cant use the ID in the loginscreen itself. The page does nothing. No errors or pop-up windows. 
Maybe you can help me (I saw some closed Issues in your git. Issue #20 ).

Thanks in advance.

**Comment by nielsengelen** [comment]
To clarify, did you add the organization using the MFA application? As you state you can use basic authentication, is this related to the same organization? You can't combine both, so it is either basic (not recommended anymore) or MFA.

**Comment by DavidCGN** [comment]
I changed the settings of an existing organization to MFA. For the restore itself I cant use the basic authentication, i have to use the Application-ID.
But I cant use the organization tenant ID with the configured Application-Id to login into the self-service portal. For the Login into the Portal itself I have to use an Domain-User that has access to the VBO365-Server.
I hope my description is better this time.

**Comment by nielsengelen** [comment]
You should be able to use the organization name (something.onmicrosoft.com) together with the application ID. Make sure there is no firewall blocking access to microsoft.com as it is required to authenticate against. Are you seeing any errors at all?

**Comment by DavidCGN** [comment]
The server can communicate with microsoft.com, but I will check our rules again. I cant see any errors, except in my browser there is a json exception error. The site doesnt time out or anything it looks like the login just doesnt work.

**Comment by nielsengelen** [comment]
Can u drop me an email niels dot engelen at veeam dot com so we can look into it with a remote call?
