### ISSUE TITLE
Veeam office 365 self service portal MFA

### ISSUE THREAD

**Issue by lmorandi777** [VeeamHub/vbo365-rest-self-service#33]
Hi, 
first thanks for Veeam office 365 self service portal. 
Basis authentication works and restore with MFA works too once connected with basic auth.
I have an issue with MFA at login. when give Tenant and application ID, I see my status connected but if I click login I'm redirect to the login page of self service portal MFA and to logged in to the portal
Could you help to fix this issue

thanks in advance 

Laurent.

**Comment by nielsengelen** [comment]
Can u clarify what you are seeing as I can't understand what the issue is you are seeing. Since you state that when using tenant and application ID, you get logged in?

**Comment by lmorandi777** [comment]
<img width="387" alt="Screenshot 2021-05-12 at 11 15 33" src="https://user-images.githubusercontent.com/84071117/117950734-cb360e00-b313-11eb-8611-3b29dd2b95a2.png">
<img width="398" alt="Screenshot 2021-05-12 at 11 17 28" src="https://user-images.githubusercontent.com/84071117/117950775-d6893980-b313-11eb-8019-badcc81c3e5a.png">

yes, see the screenshot.
I'm redirect to login page with " The provided credentials are incorrect" but if I use basic login with VBO administrator and try to restore email for example in the right organisation with MFA using credentials used to login with MFA it works

**Comment by nielsengelen** [comment]
This means that the application id or tenant id is incorrect or that the user used with the authentication via the devicelogin page lacks permissions.

**Comment by lmorandi777** [comment]
could you check the permissions please ? 

<img width="777" alt="Screenshot 2021-05-12 at 11 53 43" src="https://user-images.githubusercontent.com/84071117/117956178-17378180-b319-11eb-9922-a994e6717393.png">

**Comment by lmorandi777** [comment]
I try some permissions on 2 different user but same issue. 
below other permissions teste with another user 
<img width="695" alt="Screenshot 2021-05-12 at 12 34 05" src="https://user-images.githubusercontent.com/84071117/117961412-603e0480-b31e-11eb-9618-f59c0662bfa1.png">

**Comment by nielsengelen** [comment]
If you created the application via VBO itself, the permissions should be correct. If not, then please follow [the user guide ](https://helpcenter.veeam.com/docs/vbo365/guide/vbo_required_permissions.html?ver=50) to match those. Make sure you use the organization in the "*.onmicrosoft.com" format when going via the portal as shortnames like domain.com will not work.

**Comment by lmorandi777** [comment]
Ok, thanks, I understood my mistake. in the login field I used the tenant ID instead of the *.onmicrosoft.com.
now it's works. 
thanks a lot. really appreciated your help.

**Comment by lmorandi777** [comment]
I hope your good job will be officially deploy by Veeam.
