### ISSUE TITLE
Portal does not list all folders from sharepoint site available for restore.

### ISSUE THREAD

**Issue by jba007-dk** [VeeamHub/vbo365-rest-self-service#34]
**Describe the bug**
The problem occurs when a client has too many folders on their sharepoint site for the portal to list them.
In the veeam explorer there is an option available to "show full results" when listing folders from a sharepoint site, this option is not present in the self-service portal, and folders are not avaible to be selected for restore.

**To Reproduce**

The problem can only be reproduced when the account in question has alot of folders listed
1. Log in to with a user
2. Click sharepoint and start a restore session
3. Browse to the location with alot of folders
![veeam_explorer](https://user-images.githubusercontent.com/84385564/118644342-ffab3d80-b7dd-11eb-96b6-f88bf87f1c47.PNG)

4. Not all folders are listed, because the view is limited by default in Veeam. In the Veeam explorer for Sharepoint, there is an option to "load more results", this option is absent in the self-restore portal, and the search functionality cannot find the folders/files when they are not listed, so there are currently no option available to restore the missing folders.

**Expected behavior**
There should be an option to "load more / full list of folders"

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: tested in Chrome and Internet Explorer

**Comment by nielsengelen** [comment]
There is a load more button at the end of the page.

**Comment by jba007-dk** [comment]
Also when it comes to the "folder browser"? I cannot find any load more button?
![folder_list](https://user-images.githubusercontent.com/84385564/118646254-3eda8e00-b7e0-11eb-89d7-fb10a1c477d1.PNG)

**Comment by nielsengelen** [comment]
It will load 250 folders by default for anything (u can configure this in the config.php file), only if there are more than 250 items, the button comes available.

**Comment by jba007-dk** [comment]
Thank you, updated the config file with 1000 folders instead and restarted the site. 
For some reason there are not more folders listed.

**Comment by jba007-dk** [comment]
I have compared the view with the Veeam explorer for sharepoint.
There it can list 1096 folders which is the amount the site has.
The "Completed" folders does not exists on the sharepoint site. They not listed in the Veeam restore for sharepoint either.

Regards, Johan

**Comment by nielsengelen** [comment]
Any chance u can send me a copy of the REST API logs via mail (niels dot engelen at veeam dot com)? You can find them under %programdata%\veeam\Backup365\Logs. This way I can see if there are errors in the log and try to figure out what is causing this difference.

**Comment by jba007-dk** [comment]
Great - thanks alot - I really appreciate that.

I have send you a mail with the information requested.
