### ISSUE TITLE
Show localtime instead of UTC

### ISSUE THREAD

**Issue by eduzimrs** [VeeamHub/vbo365-rest-self-service#35]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
In the Job tab, i'd like to show the fields where contain time in localtime instead of UTC

**Describe alternatives you've considered**
Maybe add in the config.php a field to set the timezone.

**Additional context**
![Screenshot 2021-05-21 153153](https://user-images.githubusercontent.com/7524875/119182722-ae06eb00-ba49-11eb-84c7-b0d5fcdf06c9.png)

**Comment by nielsengelen** [comment]
Hi,

Sounds like a good request. This may be something easy to add in an update so I'll look into this.
