### ISSUE TITLE
Restore session cannnot be created

### ISSUE THREAD

**Issue by dominikmze** [VeeamHub/vbo365-rest-self-service#37]
Hi, 

es kann über das Portal kein Restore gefahren werden. Folgenden Fehlermeldungen erscheinenim Log: 

VBO Portal: 

[Wed Jul 14 17:45:22.973436 2021] [php7:notice] [pid 1520] [client 37.60.201.210:57198] PHP Notice:  Trying to access array offset on value of type null in /var/www/vbo365portal/veeam.php on line 93, referer: https://backup-o365.rz-owl.de/exchange/df12416a-4839-4097-8513-7ae99109a48d
[Wed Jul 14 17:45:22.973464 2021] [php7:notice] [pid 1520] [client 37.60.201.210:57198] PHP Notice:  Trying to access array offset on value of type null in /var/www/vbo365portal/veeam.php on line 94, referer: https://backup-o365.rz-owl.de/exchange/df12416a-4839-4097-8513-7ae99109a48d
[Wed Jul 14 17:45:22.973468 2021] [php7:notice] [pid 1520] [client 37.60.201.210:57198] PHP Notice:  Trying to access array offset on value of type null in /var/www/vbo365portal/veeam.php on line 96, referer: https://backup-o365.rz-owl.de/exchange/df12416a-4839-4097-8513-7ae99109a48d

Rest: 
Rest:
14.07.2021 17:45:22   40 (5752)  Action: explore
14.07.2021 17:45:22   40 (5752) Action started (action: explore, data: organizations, API version: V5)
14.07.2021 17:45:22   40 (5752) Action failed (action: explore, data: organizations, error: Restore session cannot be created.)
14.07.2021 17:45:22   40 (5752) Error: Restore session cannot be created.
14.07.2021 17:45:22   40 (5752) Type: System.Exception
14.07.2021 17:45:22   40 (5752) Stack:
14.07.2021 17:45:22   40 (5752)    bei Veeam.Core.Verifiers.Assert(Boolean b, String message, Object[] args)
   bei Veeam.Archiver.REST.Clients.RestoreSessionClient.Create(Nullable`1 organizationId, Guid jobId, DateTime pointInTime, RestoreSessionType type, Boolean showDeleted, Boolean showAllVersions)
   bei Veeam.Archiver.REST.RESTClients.RESTRestoreSessionClient.CreateForOrganizationInternal(RESTExploreOptions exploreOptions, Nullable`1 organizationId, IRequest uriSource)
   bei Veeam.Archiver.REST.Actions.OrganizationActions.Explore(JToken jsonOptions, OrganizationActionParameters parameters, IResponseBuilder responseBuilder)
   bei Veeam.REST.Actions.ActionExecutor.ExecuteActionImpl(Func`1 restAction, String actionName, IResponseBuilder responseBuilder, String dataName, IRequest uriSource, Func`1 checkData, HttpStatusCode successStatus)
   bei Veeam.REST.Actions.ActionExecutor.Execute(Func`1 restAction, String actionName, IResponseBuilder responseBuilder, String dataName, IRequest uriSource, Func`1 checkData, HttpStatusCode successStatus)

**Comment by nielsengelen** [comment]
Looks like the point in time you have selected doesn't exist or if you use "explore last backup", the point in time is not created yet (maybe a fresh install?). If you do have multiple restore points, then it could be related due to a version mismatch between the explorers and the installed VBO server.

**Comment by dominikmze** [comment]
Yes, that was the Problem thank you.
