### ISSUE TITLE
Exporting email messages getting NULL error

### ISSUE THREAD

**Issue by timwunna** [VeeamHub/vbo365-rest-self-service#39]
**Describe the bug**
Attempt to restore exchange message as pst file getting NULL error. 

**To Reproduce**
1. Go to self service Protal and login to the page
2. Click on Select a Date and click Start Restore
3. Scroll down to inbox. 
4. click on Export. (Click on Options, Restore to PST file also has same error.)
5. See error

**Expected behavior**
Should offer to save as screen and allow to change the location to restore pst file as well as file name. 

**Screenshots**
![image](https://user-images.githubusercontent.com/88997867/129508141-29ad58ac-1071-41ce-94d6-47c11d5fa1cb.png)

**Desktop (please complete the following information):**
 - Windows 2016 Std
 - Browser chrome
 - Version 91.0.4472.101

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nielsengelen** [comment]
Did you correctly install the latest Veeam Explorers and Outlook on the VBO service (used for export to PST)?

**Comment by timwunna** [comment]
Hi Niels,

I have Veeam Explores installed correctly when I upgrade the VBO to latest version available. However, I didn't realize that Outlook is required on the VBO server. I will install the outlook on the VBO server and test it. I will let you know the outcome.

Regards,
Tim

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by timwunna** [comment]
Hi Niels,

Hope you are enjoying your well deserve break. I installed outlook on VBO servers and export work like a charm now. Thanks you again.

Regards,


Timothy Liu
Compute and Storage Engineer
***@***.******@***.***>
+61 419 704 449
AUSTRALIAN – ASSURED – ACCOUNTABLE – AMPLIFIED – AGILE – ALIGNED

This email and any attachment to it are confidential. Unless you are the intended recipient, you may not use, copy or disclose either the message or any information contained in the message. If you are not the intended recipient, you should delete this email and notify the sender immediately. Any views or opinions expressed in this email are those of the sender only, unless otherwise stated.  All copyright in any AUCloud material in this email is reserved. All emails, incoming and outgoing, may be recorded by AUCloud and monitored for legitimate business purposes. AUCloud exclude all liability for any loss or damage arising or resulting from the receipt, use or transmission of this email to the fullest extent permitted by law.
