### ISSUE TITLE
Restore to orginal location fails

### ISSUE THREAD

**Issue by rmarks24** [VeeamHub/vbo365-rest-self-service#40]
**Describe the bug**
Upon trying to carry out an email restore from a users mailbox, restores to pst and msg file work, but when the user, or an admin tries to restore to original location the restore fails with one of 2 errors. either cannot open user mailbox, or Invalid length for a Base-64 char array or string.

**To Reproduce**
1. log into self service portal
2. Click on start restore session
3. Scroll down to select user mailbox
4. select item to be restored
5. click restore to original location
6. authenticate with either modern auth or legacy auth, (both see the same error.)

**Expected behavior**
Restore to start and then complete

**Screenshots**
![image](https://user-images.githubusercontent.com/80254233/132024497-f390674b-3c6f-4e0a-95b8-90b392578e42.png)
![image](https://user-images.githubusercontent.com/80254233/132024732-8a7ca2aa-4f86-4e62-89a7-60cf57218f1e.png)

**Desktop (please complete the following information):**
 - OS: windows server 2019, windows 10 and windows server 2016
 - Browser chrome or edge latest versions

**Additional context**
restore to msg or pst file completes ok

**Comment by nielsengelen** [comment]
How did you add the organization? Was this done using basic auth, MFA or MFA with legacy options?

**Comment by rmarks24** [comment]
Hi 
It was added with MFA and then changed to MFA with legacy auth.  

Regards Sent from my Huawei phone

**Comment by nielsengelen** [comment]
Any chance u can send me the REST API logs via niels dot engelen at veeam dot com?

**Comment by rmarks24** [comment]
> Any chance u can send me the REST API logs via niels dot engelen at veeam dot com?
I have found them, will send them now.
