### ISSUE TITLE
Large .pst exports don't complete to begin download via portal

### ISSUE THREAD

**Issue by adentimg** [VeeamHub/vbo365-rest-self-service#44]
**Describe the bug**
When clients try to export a large .pst via the portal the .pst never becomes available to begin downloading, we can see the .pst building when requested from the portal. Small .pst exports appear to work fine. It like there is a timeout and if reached nothing happens.

**To Reproduce**
Try and export a large mailbox

**Expected behavior**
Have the .pst file begin downloading once it has completed building

Thanks!

**Comment by nielsengelen** [comment]
Do you have an idea of the size of the mailbox or mails that you are trying to export?

**Comment by adentimg** [comment]
Hi Niels,

I now have this information.

The small .pst export that worked without issue was tiny, only ~2MB and took less than a minute to complete the export.

The larger one that failed to begin downloading via the portal is a 2.6GB .pst and from an export run via the Veeam explorer took 8 minutes to export.

Thanks.

Regards,

Aden Dyson
BackOnline Support

T  1300 733 328 / +61 8 6102 3276
NZ  +64 9280 3561
[cid:a6e08c4e-b55d-483a-89d2-48fffe64a55a]
<https://www.timg.com/solution/cloud-backup/#timg-o365>
www.timg.com<https://timgsupport.freshdesk.com/a/tickets/www.timg.com>
This e-mail may contain confidential and/or privileged information.If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. Any unauthorised copying, disclosure or distribution of the material in this e-mail is strictly forbidden.
________________________________

**Comment by nielsengelen** [comment]
Export to PST via the API is only advised for mailboxes up to 500MB. For bigger exports, it is recommended to use the explorer. This is due to the fact that the background process takes quite some time and the current API isn't able to handle this properly.
