### ISSUE TITLE
VBO v6 integration

### ISSUE THREAD

**Issue by brenoribas** [VeeamHub/vbo365-rest-self-service#46]
Hello!

I've updated my VBO to version 6 and I'm not able to perform restores anymore, then I realized there is no integration with v6.

Will we have this integration done?

Thanks!

Breno

**Comment by nielsengelen** [comment]
Hi Breno,

Did you change your config file to use v6 as an API?

**Comment by brenoribas** [comment]
Hi Niels,

Yes, I've changed the config.php file and set the version to 6, then I'm receiving the following error message on web browser:

"Invalid API version found. Modify the configuration file and configure the Veeam Backup for Microsoft Office 365 RESTful API version setting. Only version 4 and 5 are supported."

**Comment by nielsengelen** [comment]
Ah yes, that is a check in my code and requires some files to be updated. Let me check and push a change.

**Comment by nielsengelen** [comment]
I pushed an update (https://github.com/VeeamHub/vbo365-rest-self-service/commit/570fd73d3e17e076b9159eabdaf0bbe7b650db07). You'll need to replace the following files:
- index.php
- exchange.php
- onedrive.php
- sharepoint.php
- teams.php

**Comment by brenoribas** [comment]
After replacing those files, and restarting the webserver and VBO services, I'm not able to start any restore.

I'm seeing "No users found for this organization" message.

Are any other changes needed?

![image](https://user-images.githubusercontent.com/43831826/161994689-d29213c8-e89c-42c3-91a1-d5b5d81b9a97.png)

**Comment by nielsengelen** [comment]
I will have to do some extra testing to understand what causes it. What happens if you use v5 instead?

**Comment by brenoribas** [comment]
I left it as v5 in the config.php and I'm able to see the users again and start the restore, but the restore behaviour is the same as previously (keep loading the backup content forever):

![image](https://user-images.githubusercontent.com/43831826/162023752-443bf482-a6af-4d0c-b6e9-7f8b6972f660.png)

**Comment by nielsengelen** [comment]
I am unable to simulate this issue as of now. Is this by any chance a new backup job or was it still an older one that worked fine in v5?

**Comment by brenoribas** [comment]
It was working before on VBO v5, and after the upgrade, stopped to work, even changing the conf file to v5, v6.

**Comment by nielsengelen** [comment]
Would you be able to drop me an email via niels.engelen@veeam.com for follow up via logs and maybe a remote call?

**Comment by brenoribas** [comment]
Yes, I just send an email to you.

**Comment by brenoribas** [comment]
So, looks like it was an issue with VBO itself. After reinstalling the Explorer for Exchange package, I can see the items from the VBO console and web portal as well.

Also, I've decreased the number of items to be loaded on config.php from 250 to 50, but I'm not sure if it helped to fix the problem.
