### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by Ducan** [VeeamHub/vbo365-rest-self-service#5]
Good day Niels
Thank you very much for your efforts in developing the self-restore.

The self-restore portal does appear but I am unable to login with admin or tenant account.
Error: Username or password is incorrect.
Tried all various format of login credentials.  
e.g. domain\adminuser account 
For tenant I used the Office365 account and not success.

Al credentials do work when I use the explorers.

CentOS 7 with Apache & PHP 7.3
Enabled RestFulAPI on VBO with a commercial singed SSL

Any suggestions on your side what I missed in the installation process?

Thank you

**Comment by nielsengelen** [comment]
Make sure the config.php file matches the VBO API version (default is v4 but v3 works as well).

**Comment by lmbutault** [comment]
hi Niels, 

hello also have issues with login.
on my side I can log as the VBO windows admin server account.
but i don't find how to log with tenants or end users accounts.
error "Authorization Error: Invalid credential"

windows 2016, IIS.
restfull V4 or V3 with wildcard SSL
VBO V4

regards

**Comment by nielsengelen** [comment]
You can login as a tenant with the credentials used to add the organization to the VBO console however logging in with end user accounts is currently not possible.

**Comment by lmbutault** [comment]
thanks for your answer, but loging with org credentials does not seems to work in my case.

regards

**Comment by nielsengelen** [comment]
Did you enable the Authentication settings correctly: https://helpcenter.veeam.com/docs/vbo365/guide/vbo_authentication_settings.html?ver=40 ?

**Comment by lmbutault** [comment]
that was the trick, thanks you!
best wishes for 2020 and thanks for your great work.
