### ISSUE TITLE
Feature request for VBO self service portal

### ISSUE THREAD

**Issue by lmbutault** [VeeamHub/vbo365-rest-self-service#7]
hello, 

this is a great dev for now, I would suggest to make it better : 
- for tenant logins, to be able to log with any global O365 admins and not only the one defined into VBO
- for tenants logins, to have a dashboard of jobs for this organisation

 a great thing would also be for a end user to make restores of its own elements, so to have an end-user login.

regards.

**Comment by nielsengelen** [comment]
Thanks for the requests. Tenant logins is something that is on my longer todo.

The dashboard request is a new one but a great idea!
