### ISSUE TITLE
Portal Access

### ISSUE THREAD

**Issue by teratoon** [VeeamHub/vbo365-rest-self-service#9]
Hi

I have Windows Setup for self service Portal: Windows Server 2019, IIS and PHP 7.4.2. Portal is up and running, but i can't log in with Windows Administrator Credentials (Says wrong Credentials, but im sure they are correct). Server is in Workgroup. In setup.php and config.php Administrator logging is allowed

Raiko Karro

**Comment by nielsengelen** [comment]
Did you enable the authentication settings in the settings of VBO365? For using Windows admin credentials, can u try logging in as SERVER\user & the password?

**Comment by teratoon** [comment]
i'll describe my setup:

Portal is installed in Cloud Gateway server. Cloud gateway has two nics DMZ network and LAN Network. We want to separate Gateway/Portal network from LAN. VBO is installed in Cloud Connect server, which is in same LAN then Portal server. Both servers are in same domain. in VBO Autentication is enabled. If i try log to portal with domain admin or local administrator i will get user and password is incorrect.

**Comment by nielsengelen** [comment]
I tried to duplicate a scenario like this but it seems to work for me. 

Could you check the RESTful API log if something happens in there to see where the error comes from?

**Comment by teratoon** [comment]
Now i got i authentication is working, made Office365 IIS Websites and Configs from Scratch, but somehow i can't use the site. Frontpage is seeable, but if i click something i get Y"our session has expired and requires you to login again" with Chrome, it could be my IIS and PHP issue. IE is just white page, Rewrite URL's seems to be in place
